namespace: petrzpav
name: server
version: 1.0.2
readme: README.md
license:
  - MIT
authors:
  - Pavel Petrzela <paulo@internetguru.io>
repository: https://github.com/internetguru/ansible-roles
description: >-
  A collection with server roles.
