namespace: petrzpav
name: common
version: 1.1.1
readme: README.md
license:
  - MIT
authors:
  - Pavel Petrzela <paulo@internetguru.io>
repository: https://github.com/internetguru/ansible-roles
description: >-
  A collection with common roles.
